{% set version = "1.7.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-textshape
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/textshape_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/textshape/textshape_{{ version }}.tar.gz
  sha256: ba9ddfc0bc41501594fa98a09ef2808b6da7de69cfb7c3f2c542bee9bbb4314d

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-data.table
    - r-slam
    - r-stringi
  run:
    - r-base
    - r-data.table
    - r-slam
    - r-stringi

test:
  commands:
    - $R -e "library('textshape')"           # [not win]
    - "\"%R%\" -e \"library('textshape')\""  # [win]

about:
  home: http://github.com/trinker/textshape
  license: GPL-2.0-only
  summary: Tools that can be used to reshape and restructure text data.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH

# Package: textshape
# Title: Tools for Reshaping Text
# Version: 1.7.1
# Authors@R: c( person("Tyler", "Rinker", email = "tyler.rinker@gmail.com", role = c("aut", "cre")), person("Joran", "Elias", role = "ctb"), person("Matthew", "Flickinger", role = "ctb"), person('Paul', 'Foster', role = "ctb") )
# Maintainer: Tyler Rinker <tyler.rinker@gmail.com>
# Description: Tools that can be used to reshape and restructure text data.
# Depends: R (>= 3.4.0)
# Imports: data.table, slam, stats, stringi, utils
# Suggests: testthat
# License: GPL-2
# LazyData: TRUE
# RoxygenNote: 7.1.0
# URL: http://github.com/trinker/textshape
# BugReports: http://github.com/trinker/textshape/issues
# Collate: 'bind_list.R' 'bind_table.R' 'bind_vector.R' 'change_index.R' 'cluster_matrix.R' 'column_to_rownames.R' 'combine.R' 'duration.R' 'flatten.R' 'from_to.R' 'grab_index.R' 'grab_match.R' 'mtabulate.R' 'split_index.R' 'split_match.R' 'split_match_regex_to_transcript.R' 'split_portion.R' 'split_run.R' 'split_sentence.R' 'split_sentence_token.R' 'split_speaker.R' 'split_token.R' 'split_transcript.R' 'split_word.R' 'textshape-package.R' 'tidy_colo_dtm.R' 'utils.R' 'tidy_dtm.R' 'tidy_list.R' 'tidy_matrix.R' 'tidy_table.R' 'tidy_vector.R' 'unique_pairs.R' 'unnest_text.R'
# NeedsCompilation: no
# Packaged: 2020-04-17 19:55:56 UTC; trinker
# Author: Tyler Rinker [aut, cre], Joran Elias [ctb], Matthew Flickinger [ctb], Paul Foster [ctb]
# Repository: CRAN
# Date/Publication: 2020-04-17 21:00:03 UTC
