{% set version = "1.7.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-textshape
  version: {{ version|replace("-", "_") }}

source:
  fn: textshape_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/textshape_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/textshape/textshape_{{ version }}.tar.gz
  sha256: ea16c575a3e0bf577628bfbbc263435ab1a4ac5c29e8d36f2548cd39e40c2108

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-data.table
    - r-slam
    - r-stringi
  run:
    - r-base
    - r-data.table
    - r-slam
    - r-stringi

test:
  commands:
    - $R -e "library('textshape')"           # [not win]
    - "\"%R%\" -e \"library('textshape')\""  # [win]

about:
  home: http://github.com/trinker/textshape
  license: GPL-2
  summary: Tools that can be used to reshape and restructure text data.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
