{% set version = '1.6.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-textshape
  version: {{ version|replace("-", "_") }}

source:
  fn: textshape_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/textshape_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/textshape/textshape_{{ version }}.tar.gz
  sha256: 48b3eb7c929c263c8f75811e7a6bcee658480205971148db2b82e682252f88de

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-data.table
    - r-slam
    - r-stringi
  run:
    - r-base
    - r-data.table
    - r-slam
    - r-stringi

test:
  commands:
    - $R -e "library('textshape')"           # [not win]
    - "\"%R%\" -e \"library('textshape')\""  # [win]

about:
  home: http://github.com/trinker/textshape
  license: GPL-2
  summary: Tools that can be used to reshape and restructure text data.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - CurtLH
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
