travis:
  secure:
    BINSTAR_TOKEN: hRZT58HdenqenZWOmMOoQ012D15bnqc74AJ2XI1tBp/WLhIfyx5lgrw5A91UGCUdN+WuoV8/jfu2o1VfxYAlTRKTdeCukAzBd3ve0Oc7g0wlyl8MrudkCtfwc2hl9dFyOuzoKGbSxCBmCEeH8sXPoNyOILsDewJF0C/RhnVex/mHolorS8naEFxgD1HPa3Zq3JW6n+TYBGRJ4dhocmUGsXJ7LmEvEVgV2MXZ4JGR8EM/mJUGHcW42MD6suDG+YuboXWjyLGpnxfnjhaFLXk1clQlXaQdaxe7ayIElSt0YfcsFGAV8dLV9M5z1CpJfwBl+5l0WNy5xwUnj/I+458VYEF1iiPq9N1yF4G4CdkfTXSpKdmowMx1y09+zgFbLwqGoP/CL8xYfYC6cSEMySzrDStbg+I8au/SDIPK7joItVzmtk2Xp8a4qoFcyGP5VCVHSQz4ZpmnNV8gHhmu90eI9djDiJbHXdITYB3q09EkgG3eU5Ml/mCQO7miYl9nY160LXP2vFXw0x2jytnIQVRw/5NtEh/tg6SycZnMQudh7tKYsCpGGeiBUb+pWn6OO8LVqbRO98TB+jKmRh/KEmu4VIxBQUBIhiHUtIcywgx+SyaKmwQ5h0qqqTn4ccze29eZ5pVLPHR80d5mpdbDn7gogzXtyGD8+6LyZ+Fbxm4XEy0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
