appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: O5a43WkoBHV/p8T1pXbuebjabt25EBujkKp13jW4eNIhYf1utaerz1rm0YK3K1S0h5hqsXqsR+x9fLnL2JcVUgNcv/ZKMnCJzuyZGQO1vcEwjzfb7aj7Uh1k4Rampcj4YTjq3YXySrP4C7DCqSwC35CUgTca6xvBeClSGqNgUBjL1n7GXMYmAo6zKHb1Ym0cW0YffLDvBNFdeCJbuo6CMFiCOMyt8c7LNc2xen6qJiIm7bJg6jMuU2xwDqMZypqYYNBi5lcIjl/Te7P/OD+rDwQLQ/ustIVeF0AnB/D5TpgmwkxP0bP4nUYcrXlZqeyt9+AVq2tA7qX6OES+LvOdY+LSd8lCOw56aA5Te2RvmWxc7ZxiZB5zLQzqm3QWMbhErYDEXZb7lupYljT0KPctLApi1bFEqn2KJ4ncW+2t5cft2C3kUNoV+53ihXQfyiBwBe0w0srBcPVY5DwL29/IVjVIWDmcDPyiwyaaQ5IMUwwDwkkXJ5rltedG9XG60PhBNAIWXoRHO0OfiRxkHGWJtSVVh4ryv+K1rzPSfDHFmiiz0XCYepYHuhFEdUIeSel7MTzLvqjJa73rTOlvYoVlzZGEKxljKmkE5tTIXDNNG8LaR7K/I4MGZhbkrywtSsdfvjVRcrQDcaou63K+MfS7bhR3hjKaG5KepO2vE04eNLQ=
